### ISSUE TITLE
findAndConnect not working on Android 8.0

### ISSUE THREAD

**Issue by szenciattila** [devstepbcn/react-native-android-wifi#44]
RN version: 0.54
Device: Huawei P10, Android 8.0

Greetings!

Module works perfectly in past 3 month, but today I'm updated Android version from 7.1.1 to 8.0 on my phone and I realized, that it's not connecting.

I tried out with example too, but the result is the same.
On other phones with 7.1.1 Android it's working.

**Comment by szenciattila** [comment]
I just needed, to forget, network :D

**Comment by gigby** [comment]
I try to connect my test phone (samsung galaxy note 8) with camera by wi-fi. My RN (0.51) app works fine with android 6, 7, 7.1 but on 8 it can't connect to this camera.
Main problem appears due to wifi.findAndConnect() function which create new network config which doesn't work (if you connect camera manually it will work fine).
Way described above in previous comment doesn't work too.
I found only one possible way to connect camera with android 8 phone:
1) Manually connect to device (in my case it is camera ricoh)
2) Try to connect automatically via my app with this device (findAndConnect())
3) Then I remove fake config (with the same SSID) created after findAndConnect()
4) App will work fine until you manually switch the network.

Only this way this library works with android 8.
Sorry for my english.
