### ISSUE TITLE
wifi network gets duplicated

### ISSUE THREAD

**Issue by wowzaaa** [devstepbcn/react-native-android-wifi#5]
Hi

Any idea why when i do findAndConnected ... the ssid gets duplicated every time i connect to it?

thanks

**Comment by wowzaaa** [comment]
btw ... any idea on how i can disconnect from a wifi network?

**Comment by devstepbcn** [comment]
Hi wowzaa,

if each time you try to connect ssid gets duplicated, seems it's a bug. If you implement the fix send a PR, otherwise I will check it when I will have some free time.

This lib doesn't have disconnect method, but it should have it! I add this issue to the to do list! Another time, a PR will be apreciated.

I leave this issue opened.

**Comment by wowzaaa** [comment]
i will be honest with ... my knowledge base prohibits me from doing a lot of contribution since i am coming from web dev ... learning mobile now
for the disconnect part i am doing a findAndConnect with a password set to null ... which seems to disconnect from the current wifi network

i do not know if this trick use usable but i tried it and it works ... in any case ... a basic disconnect i consider to be critical for this kind of plugin

thanks

**Comment by devstepbcn** [comment]
New version published on npm includes disconnect method to disconnect device from current network.

I can't reproduce de duplication of ssid. Maybe was related to disconnect by setting the password to null on findAndConnect method. Check the sample app. Let me know if the ssid still gets duplicated.

**Comment by corymsmith** [comment]
I see duplicates as well, not sure whats going on yet though.
